version: '2'

services:
  collectd:
    image: s3ler/collectd:latest
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
    restart: always
  influxdb:
    image: hypriot/rpi-influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
    restart: always
  grafana:
    image: zeiot/rpi-grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
      - ./rpi-grafana/3.1/:/etc/grafana/
    restart: always
